### PR TITLE
Add Tally Ho wallet

### PR DESCRIPTION
**Pull request by 0xzoz**
[Tally Ho](https://tally.cash/) is an open-source community-run wallet incubated by the team at [Thesis](https://thesis.co/) and community contributors.

As we near the release of the DAO, It is essential to have the ability to put the brand front and center in applications within the ecosystem

This PR adds Tally Ho as a wallet option. It works alongside Metamask and other injected providers due to the usage of `window.tally`, which is injected by the wallet.

### CODE REVIEW

**Comment by kakui-lau** [comment]
Unable to activate the Tallyc plug-in wallet, you need to check and confirm that it can be activated and then submit your PR again.

**Comment by 0xzoz** [comment]
> After the merger, the Tally package was released, and it was confirmed by the demand that it could be confirmed, and the PR was submitted again after the merger

I had this message in my email relating to this PR, could you please elaborate?

**Comment by 0xzoz** [comment]
> Unable to activate the Tallyc plug-in wallet, you need to check and confirm that it can be activated and then submit your PR again.

Could you please give some more information? the integration worked in local tests. Maybe some screen shots etc. Why would the PR need to be sent again? Could this just be modified if there was an issue.

**Comment by 0xzoz** [comment]
I recieved some context via external chats and it looks like the issue was with bypassing `window.ethereum` with `window.tally`? What issues did this cause? It was done intentionally to allow Tally Ho to work in parralell to other injected providers.

**Comment by 0xzoz** [comment]
@kakui-lau adding a video here of the working integration. This is a video of the code in this PR. How would you like me to proceed? Apologize for the hassle and happy to work with you to get this across the line.

[Orbiter - 13 January 2023 - Watch Video](https://www.loom.com/share/b3ebd6191ffc4c34bc342888b8d653f7)

**Comment by kakui-lau** [comment]
Error prompt of connecting wallet：
Tally Ho wallet not installed or set as default wallet

window.tally is undefined

**Comment by kakui-lau** [comment]
> Error prompt of connecting wallet： Tally Ho wallet not installed or set as default wallet
> 
> window.tally is undefined

Error prompt of connecting wallet：
Tally Ho wallet not installed or set as default wallet

window.tally is undefined

**Comment by kakui-lau** [comment]
> I recieved some context via external chats and it looks like the issue was with bypassing `window.ethereum` with `window.tally`? What issues did this cause? It was done intentionally to allow Tally Ho to work in parralell to other injected providers.

Error prompt of connecting wallet：
Tally Ho wallet not installed or set as default wallet

window.tally is undefined

**Comment by 0xzoz** [comment]
> > I recieved some context via external chats and it looks like the issue was with bypassing `window.ethereum` with `window.tally`? What issues did this cause? It was done intentionally to allow Tally Ho to work in parralell to other injected providers.
> 
> Error prompt of connecting wallet： Tally Ho wallet not installed or set as default wallet
> 
> window.tally is undefined

Could you please provide some more information? 

What browser are you using?

Is Tally Ho set as default?

Is MM installed as well?

Ive tested on both Chrome and Brave with the following conditions and have not been able to reproduce the error:

- with both MM and Tally, Tally set as default
- with both MM and Tally, Tally not set as default
- without Tally and only MM installed
- with only Tally installed and no MM

**Pull request merged**
